apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}
spec:
  type: NodePort
  ports:
  - name: "vote-service"
    port: 8081
    targetPort: 80
    nodePort: 31000
  selector:
    app: {{ .Release.Name }}
  
