---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service 
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm  
spec:
  ports:
  - name: http-{{ .Release.Name }}
    protocol: TCP 
    port: {{ .Values.http.port }}
    targetPort: {{ .Values.http.targetport }}
  - name: https-{{ .Release.Name }}
    protocol: TCP
    port: {{ .Values.https.port }}
    targetPort: {{ .Values.https.targetport }}
  selector:
    app: {{ .Release.Name }}